services:

  postgres:
    container_name: contractorPostgresDB
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: contractorDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    container_name: redis-contractor
    ports:
      - "6379:6379"
    command: redis-server --requirepass pass
    volumes:
      - redis-data:/data
    restart: unless-stopped


volumes:
  rabbitmq-data:
  redis-data:
