services:
  postgres_test:
    image: postgres:17.4
    container_name: contractor_service_test_db
    environment:
      POSTGRES_DB: contractor_test_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5433:5432"