spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/contractor_test_db # Порт тестовой БД
    username: testuser
    password: testpassword
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
    drop-first: true