spring:
  application:
    name: contractor-service
  datasource:
    url: jdbc:postgresql://localhost:5432/contractorDB
    username: root
    password: pass
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: pass

jwt:
  secret: secretkeyPasswordForAuth12312312312313213123123sdfsdf

audit:
  kafka:
    enabled: false
#    topic: audit-log
#    bootstrap:
#      server: localhost:9092