spring:
  application:
    name: contractor-service
  datasource:
    url: jdbc:postgresql://localhost:5432/contractorDB
    username: root
    password: pass
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

jwt:
  secret: secretkeyPasswordForAuth12312312312313213123123sdfsdf

audit:
  kafka:
    enabled: true
    topic: audit-log
    bootstrap:
      server: localhost:9092